### ISSUE TITLE
Consider adding support for additional runtime parameters

### ISSUE THREAD

**Issue by alexngmsft** [LIS/lis-test#278]
For example, we could add following to better integrate with Jenkins.

hvServer
vmName
os
ipv4
sshKey
suite

**Comment by nickme** [comment]
Reviewed request with Chris.  At this time, the request is to allow the IPv4 item to not be specified.  If the IPv4 option is specified, LISA will use that value.  The intent is to not specify IPv4 and allow the state engine to determine the IPv4 address of the VM.

**Comment by nickme** [comment]
This has been addressed in pull request 298. Lisa no longer requires the -ipv4 argument when a test VM is specified on the command line.
