### ISSUE TITLE
create new test case for manual memory hot add

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-test#368]
@adriansuhov the test case would verify that non-aligned memory chunks can be added to a running Linux VM.
This removes the 128MB aligned memory increases as in existing releases.

**Comment by adriansuhov** [comment]
PR merged: https://github.com/LIS/lis-test/pull/369

**Comment by adriansuhov** [comment]
Test case was added: https://github.com/LIS/lis-test/pull/381
