### ISSUE TITLE
LIS deploy scenarios automation - add the selinux recommended rules

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-test#409]
LIS deploy scenarios automation should also add and validate the suggested selinux rules that are needed for the LIS daemons.
Please refer to the [LIS 4.1.x release notes](https://www.microsoft.com/en-us/download/details.aspx?id=51612) for the full documentation on the rules to be added.
@OvidiuRusu & @paulaCrismaru

**Comment by Jingli1985** [comment]
Hi Chris, 
We have a file that used to check selinux rules for LIS daemons on RHEL, I will send a PR, maybe it is helpful for this issue

**Comment by chvalean** [comment]
Merged as part of #426
