### ISSUE TITLE
Disable_NUMA_By_Kernel failure on WS2012

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-test#456]
Test case Disable_NUMA_By_Kernel fails on WS 2012 (without R2) with the below warning:
`FAILED: Could not find VmGeneration variable.`

@Jingli1985 are you able to fix this?
Thank you!

**Comment by Jingli1985** [comment]
@chvalean 
I will send PR later for this.

**Comment by chvalean** [comment]
Fixed in #461 
Thank you @Jingli1985 !
