### ISSUE TITLE
SR-IOV test cases automation

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-test#457]
Single Root I/O Virtualization (SR-IOV) specification is a standard for a type of PCI device assignment that can share a single device to multiple virtual machines. SR-IOV improves device performance for virtual machines.

SR-IOV support is present in upstream kernel and ported to newer Linux distributions.

**Comment by adriansuhov** [comment]
Automation complete, here is the PR: https://github.com/LIS/lis-test/pull/497
