### ISSUE TITLE
Use OpenSSH instead of Putty

### ISSUE THREAD

**Issue by rob-scheepens** [LIS/lis-test#663]
Would it be possible to replace the dependency on putty by implementing OpenSSH? Quick script to set this up:
```
# install Chocolatey & OpenSHH
Set-ExecutionPolicy Bypass
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y openssh -params "/SSHServerFeature"
refreshenv
```

**Comment by chvalean** [comment]
Hi Rob,

Thank you for the suggestion!
We're going to look if LISA is suitable for this and what changes it requires. We extensively use SSH commands to interact with Linux guest VMs, and there are multiple dependencies and requirements for the test environments that we have to validate.

**Comment by chvalean** [comment]
Closing item, switching to another ssh client format would involve modifying lisa from the core, up to the test cases, with a high technical debt.
We're considering newer solutions for ssh access in other automation implementations, and those might include lisa at some point.
