### ISSUE TITLE
Kdump.ps1 issue, After kdump was triggered, wait for reboot and check vmcore, but Kdump_Result.sh wasn't pushed

### ISSUE THREAD

**Issue by HiRoySoft** [LIS/lis-test#727]
Kdump.ps1
1. For Kdump_Config.sh, Kdump_Execute.sh, Kdump_Results.sh, put them into Kdump_Tests.xml <files>, they can be pushed with utils.sh together by framework. Will reduce rate of failed pushing in Kdump.ps1 script.

**Comment by chvalean** [comment]
Thank you for the suggestion @HiRoySoft 
I'm testing the changes now and submit them once validated.

Have you seen failures in the scripts being pushed? 
From our experience, as long as the VM is configured properly for lisa (keys for eg) and it starts after the kdump crash, it works as designed.
Other VM failures should be handled by LISA itself.

**Comment by HiRoySoft** [comment]
Yes. Have seen these failures several times in stress test.
As different distributions have the different booting time(I am focused on RHEL6 and RHEL7, even RHEL7 booting speed is faster than RHEL6).
Also time SSHD service prepared in every booting is different too, LISA hasn't try-again policy when push failed.
Anyway, put them into Kdump_Test.xml to push. that is will be better before test kdump.

Thanks.
