### ISSUE TITLE
Kdump_Results.sh: vm2ipv4 is null

### ISSUE THREAD

**Issue by HiRoySoft** [LIS/lis-test#729]
Kdump_Results.sh:

Code:
case $DISTRO in
        if [ $vm2ipv4 != "" ]; then
If $vm2ipv4 is not set, now above line will become if [ !=""]; then, this is a syntax error;

**Comment by chvalean** [comment]
I've looked at this now  and the vm2ipv4  variable will be parsed by kdump.ps1 to the VM, when configuring the NFS server VM as shown [here](https://github.com/LIS/lis-test/blob/master/WS2012R2/lisa/setupscripts/Kdump.ps1#L132)

If the dependency VM will not start, then the [test execution will be stopped from kdump.ps1](https://github.com/LIS/lis-test/blob/master/WS2012R2/lisa/setupscripts/Kdump.ps1#L132) , so it will never get to kdump_results.sh for the test to fail without having the variable.

The same situation applies to the other kdump test cases. Please let me know if you have some steps that you're taking and encountering the issue.

Thank you!

**Comment by HiRoySoft** [comment]
Yep, Thanks your explanation. Checked the code again. Yes, vm2ipv4 is parsed by kdump.ps1.
In case Crash_single_core, kdump_results.sh wasn't pushed to VM, so I executed kdump_results manually, got the syntax error as $vm2ipv4 is null. :)

**Comment by chvalean** [comment]
We might look in the future at re-designing on how we handle the variables in the VM - to the same model of constants.sh rather than parsing the variable directly to the guest script.
Closing the item as not fixable for the time being.
