### ISSUE TITLE
Initialize-HypervHost -git fails

### ISSUE THREAD

**Issue by olafhering** [LIS/lis-test#816]
Calling `Initialize-HypervHost.ps1 -git` fails for me, likely because `& $cmd $options` returns right away.
I'm not sure if the git-installer.exe has an option to "not fork", to make sure the ps1 scripts actually waits for git-installer.exe to return.

The following `del git-installer.exe` does also not work, likely because the file is busy. No error is reported.

Finally the test for `git.exe` fails because not much was actually installed when the "test -f $path/git.exe" is executed.

**Comment by chvalean** [comment]
I pushed the changes in https://github.com/LIS/lis-test/commit/664571741cf5ece14bf5ced6a26e19d7b3355718
Can you please check and let me know if it works fine in your environment.
Thanks Olaf!

**Comment by olafhering** [comment]
Git is not in (x86) anymore, so the "Is it installed?" part fails. Also the progress bar must be disabled, it just wastes time.

**Comment by chvalean** [comment]
Changes done, also removed the progress bar for the script.
