### ISSUE TITLE
putty md5sum location

### ISSUE THREAD

**Issue by olafhering** [LIS/lis-test#817]
InstallPutty() checks for `$filesum.Hash -ne $sums[ "x86/${util}" ]`, but the actual path in `sha256sums.txt` is w32, at least for me.

**Comment by chvalean** [comment]
Thanks @olafhering for spotting this.
It seems that Putty maintainers switched to new labels like w32 and w64. I will update the automation shortly and push the changes.

**Comment by chvalean** [comment]
Fixed in https://github.com/LIS/lis-test/commit/d907de9b5d1321ee77f383de4eeba9ebe5d84d29
