### ISSUE TITLE
Network test cases MaxSyntheticNIC, MaxLegacyNIC, MaxNIC are not stable.

### ISSUE THREAD

**Issue by lixuemin2016** [LIS/lis-test#857]
Network test cases MaxSyntheticNIC, MaxLegacyNIC, MaxNIC are not stable, get the error log "Error: Unable to set default gateway - 10.xx.xx.254".

**Comment by lixuemin2016** [comment]
@Chris, if need more information, will add.

**Comment by chvalean** [comment]
@lixuemin2016  thank you for the report.
We've done some code clean-up and stabilization in this PR https://github.com/LIS/lis-test/pull/861
Changes have been tested on RHEL 7.4 and 7.5.

Please check on your end and let me know if this is resolved.

**Comment by lixuemin2016** [comment]
Hi Chris, 
Thank you so much for change, currently it can run pass on the RHEL 7.5 vm.

Before I think maybe after add 12 NICs(4 legacy and 8 network adapter), it is hard to get valid ip address and gateway by DHCP for all the NICS, so sometimes pass, sometimes failed.  We will keep watching it during testing.

Thank you.
