### ISSUE TITLE
Disabling DM ( pre-setup ) does not work for numa cases

### ISSUE THREAD

**Issue by zqwzshm** [LIS/lis-test#865]
I met some problem recently. My ICABase checkpoint was with DM Enabled. When running numa cases ( eg. CheckNuma ), DM_DISABLE.ps1 is invoked, but it didn't actually work. Thus the the case failed.

I did a little debugging. I looks like the problem lie in DM_CONFIGURE_MEMORY.ps1: line 233.
No memory configuration will be done unless all the four parameters are present ( vmName, tpEnabled, tPstartupMem, tPmemWeight ).
While in CheckNuma case, the tPstartMemory param is not set in xml files. The memory configure part of the script is totally skipped ( and won't leave any warning message ).

I tried to do something about the code, but it looks tricky to me: 

One approach is to simply add startupMem param in all the cases invoking DM_DISABLE.ps1, which I do not think is a good way to address this problem since you would have to hard code memory size in  xml files for all cases requiring DM disable ( or even more cases ). And it is also not really reasonable to make startupMem a required param when user who just want to disable DM.

Another approach is to add an exception for the " if " in line 233 ( add an " elseif " ), which is not really safe since the script runs the whole loop when parse each param. Some unexpected behavior might happen in that way.

**Comment by zqwzshm** [comment]
Adding startupMem param in the cases is, indeed, a simple workaround anyway.

**Comment by chvalean** [comment]
Hello,
Thank you for the detailed info on it.
At least for the Core tests the DM feature will not be put to the test, especially as the tests have low resources requirements, and therefore there would be no much stress on the Dynamic Memory feature itself.
For that reason we take the feature as being not enabled - as it is by default.

I think for your situation you can simply add the required params to the CheckNuma test that will allow the DM test to properly disable and configure the VM memory settings.

**Comment by zqwzshm** [comment]
OK, thanks for reply :-)
