### ISSUE TITLE
f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault error 

### ISSUE THREAD

**Issue by lixuemin2016** [LIS/lis-test#894]
Hi Chris,

When run the latest lis-test, we get following errors during running, possibly related with following commit. https://github.com/LIS/lis-test/blob/master/WS2012R2/lisa/utilFunctions.ps1 Stop-VM $($vm.vmName) -ComputerName $($vm.hvServer) -Force -ErrorAction SilentlyContinue, when use the pull request https://github.com/LIS/lis-test/commit/13c3dffb19d2bf053ab8b1a9b4b7779e15bded14#diff-5a94f3945471067030ff7a7e991e966b.

We use the older script, it can run smoothly, but I haven't found why this commit inducing the error yet, powershell version is already 5.1, and we did not change the host.

09:19:50 Info : RHEL-7.5--GEN2-A Over-riding default snapshotName from global section to ICABase
09:19:51 Info : RHEL-7.5-.0-x86_64-GEN2-A is being reset to snapshot ICABase
09:19:51 Processing data for a remote command failed with the following error message: 
09:19:51 <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" 
09:19:51 Code="3221225477" Machine="2016-AUTO"><f:Message><f:ProviderFault 
09:19:51 provider="microsoft.powershell" path="C:\Windows\system32\pwrshplugin.dll"></f:
09:19:51 ProviderFault></f:Message></f:WSManFault> For more information, see the 
09:19:51 about_Remote_Troubleshooting Help topic.
09:19:51     + CategoryInfo          : OperationStopped: (2016-AUTO:String) [], PSRemot 
09:19:51    ingTransportException
09:19:51     + FullyQualifiedErrorId : JobFailure
09:19:51     + PSComputerName        : 2016-AUTO

Thank you so much.
Best Regards,
Xuemin

**Comment by lixuemin2016** [comment]
Update here let you know this issue, or maybe you could help to figure out the reason, thank you.

**Comment by lixuemin2016** [comment]
08:21:25 Info : DoDetermineReboot(RHEL-7.5--GEN1-A)
08:21:25 Info :    GetNextText(RHEL-7.5--GEN1-A)
08:21:25 Debug:      vm.currentTest = VMBus_verify_interrupts
08:21:25 Debug:      vm.suite = Functional
08:21:25 Info :    GetTestData(VMBus_verify_interrupts)
08:21:25 Info : RHEL-7.5-20180125.0-x86_64-GEN1-A transitioned from DetermineReboot to ShutdownSystem
08:21:25 Info : DoShutdownSystem(RHEL-7.5-20180125.0-x86_64-GEN1-A)
08:21:31 Processing data for a remote command failed with the following error message: 
08:21:31 <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" 
08:21:31 Code="3221225477" Machine="2012-72-132"><f:Message><f:ProviderFault 
08:21:31 provider="microsoft.powershell" path="C:\Windows\system32\pwrshplugin.dll"></f:
08:21:31 ProviderFault></f:Message></f:WSManFault> For more information, see the 
08:21:31 about_Remote_Troubleshooting Help topic.
08:21:31     + CategoryInfo          : OperationStopped: (2012-72-132:String) [], PSRem 
08:21:31    otingTransportException
08:21:31     + FullyQualifiedErrorId : JobFailure
08:21:31     + PSComputerName        : 2012-72-132

**Comment by chvalean** [comment]
Thank you @lixuemin2016  for the report!
We haven't seen this in our environment. How are you running lisa - is it on the same server as the test server, or you're running it from a system and use a remote Hyper-V server?

**Comment by lixuemin2016** [comment]
Hi Chris, 
We copy the lisa code from remote windows server A to test windows server B, then use following command in this remote server A to run test.

Here $env:HOST_ID is test server B.
Invoke-command -computername $env:HOST_ID -Credential $cred -scriptblock {cd "$Using:lisaDir"; .\lisa run .\xml\$Using:xmlFile -vmName $Using:vmName -hvServer $Using:hvServer -sshKey id_rsa.ppk -suite $Using:suiteTestName -os Linux -dbgLevel 10}

Thank you.

**Comment by chvalean** [comment]
I will have to check this scenario.
Usually if we target a remote Hyper-V server, we make use of the hvServer tag in the xml. The code will be executed on the VM used to run lisa, but all cmdlets will make use of the hvServer as ComputerName.

**Comment by chvalean** [comment]
@lixuemin2016 trying to repro this by only running the vmbus test case or separate test cases doesn't repro this situation.
While looking for the message, I see that some suggestions are that the wsman script execution exceeded some memory limit.
Can you please check on your servers the MaxMemoryShellMB allocation from this command:
`winrm get winrm/config/winrs`
In my case it's set to 2GB, wondering if you have a lower limit or if you run a full set of tests, maybe is your instance running out of memory?

**Comment by lixuemin2016** [comment]
Hi Chris,

Thank you so much for your great help to analyze the reason. I think you are right that maybe our instances are running out of memory during running full set of tests for lots of vms. A little strange after run the older script without this issue.

 Just checked, our host's MaxMemoryShellMB is also 2GB.  Have moved the testing hosts to other new hosts with latest scripts, it can run without this error. To avoid this issue happen again, we have reinstalled original testing hosts.

Thank you again, now I close this issue request.
