### ISSUE TITLE
hv-sock: Binaries does not work on server core without extra runtime package

### ISSUE THREAD

**Issue by zqwzshm** [LIS/lis-test#990]
Hi @ilenghel 

We have been running hv-sock-basic case, but it failed on our hosts. I tried to run the server_on_host.exe on our hosts, and did not work. I did a little digging and found that the the binaries might be built using DLL runtime library. Most of our hosts are installed with Hyper-V Server Core without extra runtime packages, which does not have the dependencies for the binaries. Would you help check about it and if it is true, it would be very helpful if you could recompile the binaries with C++ (MT) option as [Recommendation 3 in README file](https://github.com/LIS/lis-test/blob/b3d819779bbd9a1d8f24bb882167c3157cada664/WS2012R2/lisa/tools/hv-sock/README#L23).

Thank you in advance!

**Comment by ilenghel** [comment]
Hello,

I have tested the above scenario, and indeed, the Server Core on which I initially tested had the runtime libraries installed and because of that I didn't come across this issue. I recompiled the binaries and will make a PR to replace the old ones.

Thank you for pointing this out!

**Comment by zqwzshm** [comment]
Thank you very much for your help!
